#!/usr/bin/env sh

## HYPER == SHIFT + CMD + ALT + OPTION

## open emacsclient
super + control e 
	emacsclient -c

## open firefox
super + control f 
	firefox

## Open discord
super + control d
	discord
