#!/usr/bin/env sh

## HYPER == SHIFT + CMD + ALT + OPTION

## open emacsclient
super + control e 
	emacsclient -c

## open firefox
super + control f 
	firefox

## Open discord
# super + control d
# 	discord

## Rofi
super + p
	rofi -show drun

super + shift + p
	rofi -show run

## Powermenu
super + shift + q
	rofi -show power-menu -modi power-menu:~/.config/rofi/powermenu/rofi-power-menu

## Lock Screen
# super + control + l
# 	~/.bin/lock.sh

## Resource Keyboard
super + shift + S
	~/Scripts/sourceKeyboard.sh

## Pomodoro
super + shift + c
  pom finish

super + shift + v
  pom start

super + shift + b
  pom break

## Files
super + control + d
  nautilus
  
