#!/usr/bin/env sh

## HYPER == SHIFT + CMD + ALT + OPTION

## open terminal
# hyper - return : /Applications/Alacritty.app/Contents/MacOS/alacritty

## open emacs
# hyper - e : /usr/local/Cellar/emacs-mac/emacs-27.2-mac-8.3/Emacs.app/Contents/MacOS/Emacs 

## open emacsclient
hyper - f : emacsclient -c 

## opening Alacritty
hyper - t : alacritty

## opening spotify
hyper - m : /Applications/Spotify.app/Contents/MacOS/Spotify

## opening calendar
hyper - w : /System/Applications/Calendar.app/Contents/MacOS/Calendar

##### YABAI BINGINGS #####
# focus window
ctrl + shift - h : yabai -m window --focus west
ctrl + shift - j : yabai -m window --focus south
ctrl + shift - k : yabai -m window --focus north
ctrl + shift - l : yabai -m window --focus east

# swap managed window
hyper - h : yabai -m window --swap west
hyper - j : yabai -m window --swap south
hyper - k : yabai -m window --swap north
hyper - l : yabai -m window --swap east

# move managed window
shift + alt + ctrl - h : yabai -m window --warp west
shift + alt + ctrl - j : yabai -m window --warp south
shift + alt + ctrl - k : yabai -m window --warp north
shift + alt + ctrl - l : yabai -m window --warp east

# rotate tree
alt - r : yabai -m space --rotate 90

# toggle window fullscreen zoom
alt - f : yabai -m window --toggle zoom-fullscreen

# toggle padding and gap
alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

# float / unfloat window and center on screen
alt - t : yabai -m window --toggle float;\
          yabai -m window --grid 4:4:1:1:2:2

# toggle window split type
alt - e : yabai -m window --toggle split

# balance size of windows
ctrl - 0 : yabai -m space --balance

# move window and focus desktop
hyper - 1 : yabai -m window --space 1; yabai -m space --focus 1
hyper - 2 : yabai -m window --space 2; yabai -m space --focus 2
hyper - 3 : yabai -m window --space 3; yabai -m space --focus 3
hyper - 4 : yabai -m window --space 4; yabai -m space --focus 4
hyper - 5 : yabai -m window --space 5; yabai -m space --focus 5
hyper - 6 : yabai -m window --space 6; yabai -m space --focus 6
hyper - 7 : yabai -m window --space 7; yabai -m space --focus 7
hyper - 8 : yabai -m window --space 8; yabai -m space --focus 8
hyper - 9 : yabai -m window --space 9; yabai -m space --focus 9

# Applescript to create and remove desktops
hyper - n : osascript ~/tools/New\ Desktop.scpt
hyper - d : osascript ~/tools/Close\ Desktop.scpt

# fast focus desktop
alt - 0 : yabai -m space --focus recent

# send window to monitor and follow focus
shift + alt - n : yabai -m window --display next; yabai -m display --focus next
shift + alt - p : yabai -m window --display previous; yabai -m display --focus previous

# increase window size
shift + alt - w : yabai -m window --resize top:0:-20
shift + alt - d : yabai -m window --resize left:-20:0

# decrease window size
shift + alt - s : yabai -m window --resize bottom:0:-20
shift + alt - a : yabai -m window --resize top:0:20
